// src/components/AppLayout.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ROLE_LABEL, type Role } from '../lib/roles'
import { useAuthStore } from '../stores/auth'
import ThemeToggle from './ThemeToggle.vue'
import BaseButton from './ui/BaseButton.vue'

/**
 * โครงหน้าจอร่วมของทุกหน้าหลังล็อกอิน
 *
 * เพิ่มเมนูใหม่ = แก้ NAV ที่เดียว
 * เมนูที่ role ไม่ถึงจะไม่ถูกเรนเดอร์ แต่นั่นเป็นแค่การซ่อน —
 * router.beforeEach กันที่ route และ BE กันอีกชั้น
 */
const auth = useAuthStore()
const router = useRouter()
const busy = ref(false)

const NAV: { to: string; label: string; min?: Role }[] = [
  { to: '/dashboard', label: 'แดชบอร์ด' },
  { to: '/events', label: 'Network Event' },
  { to: '/users', label: 'จัดการผู้ใช้', min: 'admin' },
]

const items = computed(() => NAV.filter((n) => !n.min || auth.can(n.min)))

async function handleLogout() {
  busy.value = true
  await auth.logout()
  router.replace({ name: 'login' })
}
</script>

<template>
  <div class="flex min-h-full flex-col">
    <header class="sticky top-0 z-40 border-b border-base-300 bg-base-100">
      <div class="mx-auto flex max-w-6xl flex-wrap items-center gap-x-6 gap-y-2 px-4 py-3">
        <span class="font-semibold tracking-tight">R4</span>

        <nav class="flex flex-1 flex-wrap items-center gap-1">
          <RouterLink
            v-for="n in items"
            :key="n.to"
            :to="n.to"
            class="btn btn-sm btn-ghost font-normal"
            active-class="btn-active font-medium"
          >
            {{ n.label }}
          </RouterLink>
        </nav>

        <div class="flex items-center gap-2">
          <span class="hidden text-sm opacity-70 sm:inline">
            {{ auth.user?.fullName ?? auth.user?.username }}
            <template v-if="auth.user"> · {{ ROLE_LABEL[auth.user.role] }}</template>
          </span>
          <ThemeToggle />
          <BaseButton variant="ghost" size="sm" :loading="busy" @click="handleLogout">
            ออกจากระบบ
          </BaseButton>
        </div>
      </div>
    </header>

    <main class="mx-auto w-full max-w-6xl flex-1 px-4 py-8">
      <slot />
    </main>
  </div>
</template>

// src/components/app-layout.tsx
import { useState, type ReactNode } from 'react'
import { NavLink, useNavigate } from 'react-router-dom'
import { useAuth } from '../lib/auth-context'
import { atLeast, ROLE_LABEL, type Role } from '../lib/roles'
import { ThemeToggle } from './theme-toggle'
import { Button } from './ui'

type NavItem = { to: string; label: string; min?: Role }

const NAV: NavItem[] = [
  { to: '/dashboard', label: 'แดชบอร์ด' },
  { to: '/events', label: 'Network Event' },
  { to: '/users', label: 'จัดการผู้ใช้', min: 'admin' },
]

/**
 * โครงหน้าจอที่ใช้ร่วมกันทุกหน้าหลังล็อกอิน
 *
 * ทำตอนที่มี 4 หน้าแล้ว ไม่รอให้ครบ 6 — header ที่ก๊อปกันไว้แต่ละหน้าเริ่มเพี้ยนจากกัน
 * เร็วกว่าที่คิดเสมอ พอมีที่เดียวแล้วเพิ่มเมนูใหม่ก็แก้แค่ NAV ข้างบน
 *
 * เมนูที่ role ไม่ถึงจะไม่ถูกเรนเดอร์ แต่นั่นเป็นแค่การซ่อน — RequireRole กันที่ route
 * และ BE กันอีกชั้น คนพิมพ์ URL เองยังเข้าไม่ได้อยู่ดี
 */
export function AppLayout({ children }: { children: ReactNode }) {
  const { user, logout } = useAuth()
  const navigate = useNavigate()
  const [busy, setBusy] = useState(false)

  const items = NAV.filter((n) => !n.min || atLeast(user?.role, n.min))

  async function handleLogout() {
    setBusy(true)
    await logout()
    navigate('/login', { replace: true })
  }

  return (
    <div className="flex min-h-full flex-col">
      <header
        className="sticky top-0 z-40 border-b"
        style={{ background: 'var(--surface)', borderColor: 'var(--border)' }}
      >
        <div className="mx-auto flex max-w-6xl flex-wrap items-center gap-x-6 gap-y-2 px-4 py-3">
          <span className="font-semibold tracking-tight">R4</span>

          <nav className="flex flex-1 flex-wrap items-center gap-1">
            {items.map((n) => (
              <NavLink
                key={n.to}
                to={n.to}
                className="rounded-md px-2.5 py-1.5 text-sm transition-colors"
                style={({ isActive }) => ({
                  background: isActive ? 'var(--surface-2)' : 'transparent',
                  color: isActive ? 'var(--text)' : 'var(--text-muted)',
                  fontWeight: isActive ? 500 : 400,
                })}
              >
                {n.label}
              </NavLink>
            ))}
          </nav>

          <div className="flex items-center gap-2">
            <span className="hidden text-sm sm:inline" style={{ color: 'var(--text-muted)' }}>
              {user?.fullName ?? user?.username}
              {user && ` · ${ROLE_LABEL[user.role]}`}
            </span>
            <ThemeToggle />
            <Button variant="ghost" onClick={handleLogout} loading={busy}>
              ออกจากระบบ
            </Button>
          </div>
        </div>
      </header>

      <main className="mx-auto w-full max-w-6xl flex-1 px-4 py-8">{children}</main>
    </div>
  )
}

/** หัวข้อของแต่ละหน้า + ที่วางปุ่มด้านขวา */
export function PageHeader({
  title, description, actions,
}: { title: string; description?: string; actions?: ReactNode }) {
  return (
    <div className="mb-6 flex flex-wrap items-start justify-between gap-4">
      <div>
        <h1 className="text-xl font-semibold tracking-tight">{title}</h1>
        {description && (
          <p className="mt-1 text-sm" style={{ color: 'var(--text-muted)' }}>{description}</p>
        )}
      </div>
      {actions && <div className="flex flex-wrap items-center gap-2">{actions}</div>}
    </div>
  )
}
